### ISSUE TITLE
Obtain GO terms applicable to taxon

### ISSUE THREAD

**Issue by wkpalan** [geneontology/helpdesk#216]
I am trying to obtain GO terms that are applicable to a given taxon such as fungi or insects. I gather that owltools can be used for that purpose with go-plus.owl file. However when I run the following command

    owltools go-plus.owl --make-taxon-set NCBITaxon_33090

The command errors out with the error message

    Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4779)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
        at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
    Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.HashSet.<init>(HashSet.java:106)
        at owltools.graph.OWLGraphEdge$OWLGraphEdgeSet.<init>(OWLGraphEdge.java:39)
        at owltools.graph.OWLGraphWrapperEdges.getOutgoingEdgesViaReverseUnion(OWLGraphWrapperEdges.java:303)
        at owltools.graph.OWLGraphWrapperEdges.getPrimitiveOutgoingEdges(OWLGraphWrapperEdges.java:361)
        at owltools.graph.OWLGraphWrapperEdges.getOutgoingEdgesClosure(OWLGraphWrapperEdges.java:851)
        at owltools.graph.OWLGraphWrapperEdges.getOutgoingEdgesClosure(OWLGraphWrapperEdges.java:805)
        at owltools.cli.TaxonCommandRunner.makeTaxonSet(TaxonCommandRunner.java:107)
        ... 8 more

I was wondering if this was something to do with `owltools` or the `go-plus.owl` file

**Comment by kltm** [comment]
Any uncaught exception is probably going to be caused by the software, so you might want to open a ticket at https://github.com/owlcollab/owltools . That said, in this case, you have "Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded", which likely means that you do not have enough memory to run the tool.

**Comment by wkpalan** [comment]
Thank you for pointing me on the right direction about the memory issue, I missed it completely. Seems like the documentation is a little unclear about these things. After setting higher memory limits and setting a few other options it seems to be working fine so far.  I will ask any more questions on the tool git hub page.
